In [1]:
import pandas as pd

In [2]:
train=pd.read_csv('train.csv')

In [3]:
test=pd.read_csv('test.csv')

In [4]:
train.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [5]:
test.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        7613 non-null   int64 
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 297.5+ KB


In [7]:
train.isnull().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [8]:
train.drop('location',axis=1,inplace=True)

In [9]:
train.dropna(inplace=True)

In [10]:
train

id  keyword                                               text  \
31       48   ablaze  @bbcmtd Wholesale Markets ablaze http://t.co/l...   
32       49   ablaze  We always try to bring the heavy. #metal #RT h...   
33       50   ablaze  #AFRICANBAZE: Breaking news:Nigeria flag set a...   
34       52   ablaze                 Crying out for more! Set me ablaze   
35       53   ablaze  On plus side LOOK AT THE SKY LAST NIGHT IT WAS...   
...     ...      ...                                                ...   
7578  10830  wrecked   @jt_ruff23 @cameronhacker and I wrecked you both   
7579  10831  wrecked  Three days off from work and they've pretty mu...   
7580  10832  wrecked  #FX #forex #trading Cramer: Iger's 3 words tha...   
7581  10833  wrecked  @engineshed Great atmosphere at the British Li...   
7582  10834  wrecked  Cramer: Iger's 3 words that wrecked Disney's s...   

      target  
31         1  
32         0  
33         1  
34         0  
35         0  
...      ...  
7578       0  
7579       0  
7580       0  
7581       0  
7582       0  

[7552 rows x 4 columns]

In [11]:
train['text']=train['text'].astype(str).apply(lambda x: x.lower())

In [12]:
train['text'] = train['text'].str.replace('http\S+|www.\S+', '', case=False)

In [13]:
import nltk
from nltk.corpus import stopwords
import string

In [14]:
def text_process(text):
    

    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [15]:
train['text']=train['text'].apply(text_process)

In [16]:
train['text'][31]

['bbcmtd', 'wholesale', 'markets', 'ablaze']

In [17]:
train

id  keyword                                               text  \
31       48   ablaze               [bbcmtd, wholesale, markets, ablaze]   
32       49   ablaze             [always, try, bring, heavy, metal, rt]   
33       50   ablaze  [africanbaze, breaking, newsnigeria, flag, set...   
34       52   ablaze                              [crying, set, ablaze]   
35       53   ablaze       [plus, side, look, sky, last, night, ablaze]   
...     ...      ...                                                ...   
7578  10830  wrecked                 [jtruff23, cameronhacker, wrecked]   
7579  10831  wrecked  [three, days, work, theyve, pretty, much, wrec...   
7580  10832  wrecked  [fx, forex, trading, cramer, igers, 3, words, ...   
7581  10833  wrecked  [engineshed, great, atmosphere, british, lion,...   
7582  10834  wrecked  [cramer, igers, 3, words, wrecked, disneys, st...   

      target  
31         1  
32         0  
33         1  
34         0  
35         0  
...      ...  
7578       0  
7579       0  
7580       0  
7581       0  
7582       0  

[7552 rows x 4 columns]

In [18]:
train.drop('id',axis=1,inplace=True)

In [19]:
train

keyword                                               text  target
31     ablaze               [bbcmtd, wholesale, markets, ablaze]       1
32     ablaze             [always, try, bring, heavy, metal, rt]       0
33     ablaze  [africanbaze, breaking, newsnigeria, flag, set...       1
34     ablaze                              [crying, set, ablaze]       0
35     ablaze       [plus, side, look, sky, last, night, ablaze]       0
...       ...                                                ...     ...
7578  wrecked                 [jtruff23, cameronhacker, wrecked]       0
7579  wrecked  [three, days, work, theyve, pretty, much, wrec...       0
7580  wrecked  [fx, forex, trading, cramer, igers, 3, words, ...       0
7581  wrecked  [engineshed, great, atmosphere, british, lion,...       0
7582  wrecked  [cramer, igers, 3, words, wrecked, disneys, st...       0

[7552 rows x 3 columns]

In [20]:
train['text']=train['text'].astype(str)
train['tex']=train['text']+train['keyword']
train.drop(['keyword','text'],axis=1,inplace=True)

In [21]:
train

target                                                tex
31         1  ['bbcmtd', 'wholesale', 'markets', 'ablaze']ab...
32         0  ['always', 'try', 'bring', 'heavy', 'metal', '...
33         1  ['africanbaze', 'breaking', 'newsnigeria', 'fl...
34         0                  ['crying', 'set', 'ablaze']ablaze
35         0  ['plus', 'side', 'look', 'sky', 'last', 'night...
...      ...                                                ...
7578       0    ['jtruff23', 'cameronhacker', 'wrecked']wrecked
7579       0  ['three', 'days', 'work', 'theyve', 'pretty', ...
7580       0  ['fx', 'forex', 'trading', 'cramer', 'igers', ...
7581       0  ['engineshed', 'great', 'atmosphere', 'british...
7582       0  ['cramer', 'igers', '3', 'words', 'wrecked', '...

[7552 rows x 2 columns]

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB


In [23]:
from sklearn.model_selection import train_test_split
X=train['tex']
y=train['target']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=101)

In [24]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('bow', CountVectorizer(analyzer=text_process)),  # strings to token integer counts
    ('tfidf', TfidfTransformer()),  # integer counts to weighted TF-IDF scores
    ('classifier', MultinomialNB()),  # train on TF-IDF vectors w/ Naive Bayes classifier
])

In [25]:
pipeline.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('bow',
                 CountVectorizer(analyzer=<function text_process at 0x0000023D060DB3A8>,
                                 binary=False, decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('classifier',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [26]:
predictions = pipeline.predict(X_test)

In [27]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[1191  136]
 [ 315  624]]
              precision    recall  f1-score   support

           0       0.79      0.90      0.84      1327
           1       0.82      0.66      0.73       939

    accuracy                           0.80      2266
   macro avg       0.81      0.78      0.79      2266
weighted avg       0.80      0.80      0.80      2266



In [28]:
print(pipeline.score(X_train,y_train))

0.9224366250472947


In [29]:
predictions=pipeline.predict(test)

In [30]:
predictions

array([0, 0, 1, 0], dtype=int64)

In [31]:
import pickle

In [32]:
filename = 'model'
outfile = open(filename,'wb')
pickle.dump(pipeline,outfile)
outfile.close()

In [33]:
test.drop('location',axis=1,inplace=True)
test.drop('id',axis=1,inplace=True)
test.dropna(inplace=True)

In [34]:
test['text']=test['text'].astype(str).apply(lambda x: x.lower())
test['text'] = test['text'].str.replace('http\S+|www.\S+', '', case=False)

In [35]:
import nltk
from nltk.corpus import stopwords
import string

def text_process(text):
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [36]:
test['text']=test['text'].apply(text_process)

In [37]:
test

keyword                                               text
15     ablaze  [birmingham, wholesale, market, ablaze, bbc, n...
16     ablaze       [sunkxssedharry, wear, shorts, race, ablaze]
17     ablaze  [previouslyondoyintv, toke, makinwa‰ûªs, marri...
18     ablaze                                      [check, nsfw]
19     ablaze  [psa, i‰ûªm, splitting, personalities, techies...
...       ...                                                ...
3247  wrecked  [rt, cnbc, 3, words, disney, ceo, bob, iger, w...
3248  wrecked  [smackdown, tyme, put, good, mood, since, got,...
3249  wrecked  [thrillhho, jsyk, havent, stopped, thinking, a...
3250  wrecked  [stighefootball, begovic, garbage, got, wrecke...
3251  wrecked                    [wrecked, today, got, hattrick]

[3237 rows x 2 columns]

In [38]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3237 entries, 15 to 3251
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   keyword  3237 non-null   object
 1   text     3237 non-null   object
dtypes: object(2)
memory usage: 75.9+ KB


In [39]:
test['text']=test['text'].astype(str)
test['modified_text']=test['text']+test['keyword']
test.drop(['keyword','text'],axis=1,inplace=True)

In [40]:
test

modified_text
15    ['birmingham', 'wholesale', 'market', 'ablaze'...
16    ['sunkxssedharry', 'wear', 'shorts', 'race', '...
17    ['previouslyondoyintv', 'toke', 'makinwa\x89ûª...
18                              ['check', 'nsfw']ablaze
19    ['psa', 'i\x89ûªm', 'splitting', 'personalitie...
...                                                 ...
3247  ['rt', 'cnbc', '3', 'words', 'disney', 'ceo', ...
3248  ['smackdown', 'tyme', 'put', 'good', 'mood', '...
3249  ['thrillhho', 'jsyk', 'havent', 'stopped', 'th...
3250  ['stighefootball', 'begovic', 'garbage', 'got'...
3251     ['wrecked', 'today', 'got', 'hattrick']wrecked

[3237 rows x 1 columns]

In [41]:
import pickle
infile = open('model','rb')
load_model = pickle.load(infile)
infile.close()
print(type(load_model))

<class 'sklearn.pipeline.Pipeline'>


In [42]:
test

modified_text
15    ['birmingham', 'wholesale', 'market', 'ablaze'...
16    ['sunkxssedharry', 'wear', 'shorts', 'race', '...
17    ['previouslyondoyintv', 'toke', 'makinwa\x89ûª...
18                              ['check', 'nsfw']ablaze
19    ['psa', 'i\x89ûªm', 'splitting', 'personalitie...
...                                                 ...
3247  ['rt', 'cnbc', '3', 'words', 'disney', 'ceo', ...
3248  ['smackdown', 'tyme', 'put', 'good', 'mood', '...
3249  ['thrillhho', 'jsyk', 'havent', 'stopped', 'th...
3250  ['stighefootball', 'begovic', 'garbage', 'got'...
3251     ['wrecked', 'today', 'got', 'hattrick']wrecked

[3237 rows x 1 columns]

In [43]:
print(type(test))

<class 'pandas.core.frame.DataFrame'>


In [44]:
new_test=test.T
new_test=new_test.iloc[0]


In [45]:
new_test

15      ['birmingham', 'wholesale', 'market', 'ablaze'...
16      ['sunkxssedharry', 'wear', 'shorts', 'race', '...
17      ['previouslyondoyintv', 'toke', 'makinwa\x89ûª...
18                                ['check', 'nsfw']ablaze
19      ['psa', 'i\x89ûªm', 'splitting', 'personalitie...
                              ...                        
3247    ['rt', 'cnbc', '3', 'words', 'disney', 'ceo', ...
3248    ['smackdown', 'tyme', 'put', 'good', 'mood', '...
3249    ['thrillhho', 'jsyk', 'havent', 'stopped', 'th...
3250    ['stighefootball', 'begovic', 'garbage', 'got'...
3251       ['wrecked', 'today', 'got', 'hattrick']wrecked
Name: modified_text, Length: 3237, dtype: object

In [46]:
print(type(new_test))

<class 'pandas.core.series.Series'>


In [49]:
load_model.predict(new_test)

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)